/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import interfaces.SolicitacaoInterface;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Produto;
import model.Solicitacao;
import repository.ProdutoRep;
import repository.SolicitacaoRep;

/**
 *
 * @author Vine
 */
public class TelaAprovaSolicitacao extends javax.swing.JFrame {
    String statusAtual;
    int cod;
    int qtdEstoque;
    int qtd;
    
    private SolicitacaoInterface sol = new SolicitacaoInterface();
    
    public TelaAprovaSolicitacao() {
        initComponents();
        refreshSolicitacaoTable();
       
        txtTotal.setEditable(false);
        centralizar();
    }
    public void centralizar(){
        setLocationRelativeTo(null);
    }
    

    private void refreshSolicitacaoTable(){
        SolicitacaoRep lis = new SolicitacaoRep();
        sol = new SolicitacaoInterface(lis.listar());
        tblSolicitacao.setModel(sol);
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolicitacao = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cmbStatus = new javax.swing.JComboBox<>();
        txtTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblSolicitacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblSolicitacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSolicitacaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSolicitacao);

        jLabel1.setText("Solicitação de Produto");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jButton3.setText("Voltar");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aprovar", "Reprovar" }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });

        jLabel2.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Solicitacao solicitacao = new Solicitacao();
        SolicitacaoRep srep = new SolicitacaoRep();
        
        solicitacao.setCodProduto(cod);
        String cmbSel = cmbStatus.getSelectedItem().toString();
        if(cmbSel.equalsIgnoreCase("Aprovar")){
            cmbSel = "Aprovado";
        }else if (cmbSel.equalsIgnoreCase("Reprovar")){
            cmbSel = "Reprovado";
        }
        
                
        if (statusAtual.equalsIgnoreCase("Pendente")) {
            solicitacao.setStatus(cmbSel);
            srep.alterarSolicitacao(solicitacao);
            
                ProdutoRep prep = new ProdutoRep();
                Produto pod = new Produto();
               
                 
                prep.listar();
                
                pod.setCodProduto(cod);
                pod.setQtdEstoque(qtdEstoque + qtd);
                
                 
                prep.alterarsalvar(pod);
                refreshSolicitacaoTable();

             
            
        } 
        else {
            JOptionPane.showMessageDialog(null, "Operação Nao Concluída! \nSó é possivel alterar status Quando 'Pendente!' ");
        }
        refreshSolicitacaoTable();

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tblSolicitacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSolicitacaoMouseClicked
        int linha = tblSolicitacao.getSelectedRow();
        Produto pod = new Produto();
        ProdutoRep prep = new ProdutoRep();
        
        
        
        
        
        qtd = Integer.parseInt(tblSolicitacao.getValueAt(linha, 4).toString());
        BigDecimal custo = BigDecimal.valueOf(Double.parseDouble(tblSolicitacao.getValueAt(linha, 2).toString()));
        Double custoDouble = custo.doubleValue();
        double TotalTotal = qtd * custoDouble;
        txtTotal.setText(Double.toString(TotalTotal));
        qtdEstoque = qtdEstoque + qtd;
        statusAtual = tblSolicitacao.getValueAt(linha, 5).toString();
        cod = Integer.parseInt(tblSolicitacao.getValueAt(linha, 0).toString());
        

    }//GEN-LAST:event_tblSolicitacaoMouseClicked

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAprovaSolicitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAprovaSolicitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAprovaSolicitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAprovaSolicitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAprovaSolicitacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSolicitacao;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
